export const styles = [
    {
        "id": 133,
        "name": "رتروپاپ",
        "is_visible": true,
        "created_at": "2024-02-16T19:22:24.029815Z",
        "updated_at": "2030-12-29T12:04:59Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/retro_pop_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": true,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAhEAABBAEDBQAAAAAAAAAAAAABAAIDBAUGESEHEyIxQf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAYEQEAAwEAAAAAAAAAAAAAAAABAAISIf/aAAwDAQACEQMRAD8Ajcj1a1FTy15s0WKvGSXuB9um17owWt8GkbbNHwc+zyiIjpODDZSyE//Z"
    },
    {
        "id": 132,
        "name": "لوگو",
        "is_visible": true,
        "created_at": "2024-02-09T19:32:16.233126Z",
        "updated_at": "2030-12-29T12:03:59Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/logo_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": true,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAiEAAABQIHAQAAAAAAAAAAAAAAAQIDBQQTBhEUFSEiQSP/xAAUAQEAAAAAAAAAAAAAAAAAAAAE/8QAGBEAAgMAAAAAAAAAAAAAAAAAAAECMVH/2gAMAwEAAhEDEQA/AIRieSbrNpNMVGUtqPZaPTMW7pln9F89ln6r0AAIVCXFYf/Z"
    },
    {
        "id": 131,
        "name": "استیکر",
        "is_visible": true,
        "created_at": "2024-02-02T19:58:09.173881Z",
        "updated_at": "2030-12-29T12:02:59Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/sticker_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": true,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAfEAABBAICAwAAAAAAAAAAAAABAAIDBAUREjEGEyH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABYRAQEBAAAAAAAAAAAAAAAAAAEAEf/aAAwDAQACEQMRAD8Aiz+XysgqC3hcFePq2x1in9iYXuIjbwLRxb0N7OuyURFGsoX/2Q=="
    },
    {
        "id": 130,
        "name": "اچ‌دی‌آر",
        "is_visible": true,
        "created_at": "2024-01-26T20:30:48.143112Z",
        "updated_at": "2030-12-29T12:01:59Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/hdr_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": true,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAfEAABBQABBQAAAAAAAAAAAAABAAIDBREEBhMhImH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABYRAAMAAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8AmPVHOZNFRtlr693ZrIYmkQBvqC7NzNP0+URENZXEf//Z"
    },
    {
        "id": 129,
        "name": "طراحی مداد",
        "is_visible": true,
        "created_at": "2024-01-19T19:14:21.877726Z",
        "updated_at": "2030-12-29T12:00:59Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/sketch_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAdEAABAwUBAAAAAAAAAAAAAAABAAIDBAUGEiEi/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCm4LDWyy5ORebmxgvdTpGJGlrB5OrdmkgdPERFJf/Z"
    },
    {
        "id": 128,
        "name": "کاریکاتور",
        "is_visible": true,
        "created_at": "2024-01-12T20:55:17.179617Z",
        "updated_at": "2030-12-29T12:00:58Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/cartoonist_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAeEAACAgICAwAAAAAAAAAAAAABAgAEAwUGIRETMf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAZEQACAwEAAAAAAAAAAAAAAAAAAQIDESH/2gAMAwEAAhEDEQA/AI1zmPIaW02DYNzfAtZzZZPewVGYDyFAPS9fIiI9a2K0Gb6f/9k="
    },
    {
        "id": 122,
        "name": "طراحی جوهر",
        "is_visible": true,
        "created_at": "2023-10-06T19:04:56.570067Z",
        "updated_at": "2030-12-28T12:00:58Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/ink_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAfEAAABgIDAQAAAAAAAAAAAAAAAQIDBBEFMQYTFCH/xAAVAQEBAAAAAAAAAAAAAAAAAAABA//EABYRAQEBAAAAAAAAAAAAAAAAAAEAEf/aAAwDAQACEQMRAD8AqJXIs1gFoSxlpsop6Ez1et03OpThWbbeqbKvhHdXsAAGFMW//9k="
    },
    {
        "id": 126,
        "name": "انیمه",
        "is_visible": true,
        "created_at": "2023-12-29T21:47:27.94649Z",
        "updated_at": "2030-12-28T12:00:58Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/anime_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAfEAAABgEFAAAAAAAAAAAAAAAAAQIDBAUSBgcRQVH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGBEAAgMAAAAAAAAAAAAAAAAAAAECETH/2gAMAwEAAhEDEQA/AINLuTqGloq2vrHIkeIwzihBRkK4LJR9kfoAAGSVjLD/2Q=="
    },
    {
        "id": 127,
        "name": "کمیک",
        "is_visible": true,
        "created_at": "2024-01-05T19:46:53.626802Z",
        "updated_at": "2030-12-28T12:00:58Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/comic_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAiEAAABQMEAwAAAAAAAAAAAAAAAgMEBQEHERITISIUI0H/xAAVAQEBAAAAAAAAAAAAAAAAAAACBP/EABcRAAMBAAAAAAAAAAAAAAAAAAABIQL/2gAMAwEAAhEDEQA/AK1sbgzSkVJuHfjulHEgqt7ymNt6ik6E7cEpzinzNQAAWqV6VP/Z"
    },
    {
        "id": 124,
        "name": "خیالی",
        "is_visible": true,
        "created_at": "2023-11-03T17:23:40.090713Z",
        "updated_at": "2030-12-28T12:00:58Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/whimsical_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAeEAACAgICAwAAAAAAAAAAAAABAwIEAAUGESFBUf/EABUBAQEAAAAAAAAAAAAAAAAAAAQF/8QAGxEBAAICAwAAAAAAAAAAAAAAAQACAxFxkbH/2gAMAwEAAhEDEQA/AIlfnO2Vx/R2WRrWGXKsnSDYExV09qxBYBAjARWPH0k+8YxkdDby+xNstx0We5//2Q=="
    },
    {
        "id": 121,
        "name": "فانتزی",
        "is_visible": true,
        "created_at": "2023-09-29T18:46:39.717765Z",
        "updated_at": "2029-12-28T12:00:59Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/dark_fantasy_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAgEAABBAIBBQAAAAAAAAAAAAACAAEDBAURUQYSExUi/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABYRAQEBAAAAAAAAAAAAAAAAAAARAf/aAAwDAQACEQMRAD8An+e6lyuH9bXgtlPCVGEwGx9+Fu3TAHAtrbNy7oiJ6Apj/9k="
    },
    {
        "id": 123,
        "name": "وحشت",
        "is_visible": true,
        "created_at": "2023-10-20T20:27:26.093181Z",
        "updated_at": "2029-12-28T12:00:59Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/horror_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAdEAABBQADAQAAAAAAAAAAAAABAAIDBBEFBhMh/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/xAAXEQEBAQEAAAAAAAAAAAAAAAABAgAh/9oADAMBAAIRAxEAPwCVdr71ykFqlG2txj4W0ofKOWo2UQMLdEbC7SGDTg34iIhxIyc1O1KQ3//Z"
    },
    {
        "id": 115,
        "name": "تخیلی",
        "is_visible": true,
        "created_at": "2023-07-17T20:41:39.967577Z",
        "updated_at": "2029-12-28T12:00:58Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/dreamland_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAj/xAAeEAACAgEFAQAAAAAAAAAAAAABAgADBAUGERIhE//EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFxEBAAMAAAAAAAAAAAAAAAAAAQACEf/aAAwDAQACEQMRAD8An3WdzZeZm9mow6RUi0KlFXzXqgCgkA+seOST6STERK1XIGps/9k="
    },
    {
        "id": 120,
        "name": "باروک",
        "is_visible": true,
        "created_at": "2023-09-22T20:40:41.6878Z",
        "updated_at": "2029-12-28T12:00:58Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/baroque_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAdEAACAgIDAQAAAAAAAAAAAAABAgADBBEFEiEi/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABgRAAIDAAAAAAAAAAAAAAAAAAABAiIx/9oADAMBAAIRAxEAPwCd8nSeUyBmC2zCe1R3TDC1o7L89yNHbEAbJ9JiIg8FVCz0/9k="
    },
    {
        "id": 119,
        "name": "هیولا",
        "is_visible": true,
        "created_at": "2023-08-25T22:20:00.640985Z",
        "updated_at": "2029-12-28T12:00:57Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/monster_v3.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAdEAACAgIDAQAAAAAAAAAAAAABAgMRAAQTIUFR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwX/xAAYEQEBAQEBAAAAAAAAAAAAAAABAgARIf/aAAwDAQACEQMRAD8AjZZk21i59bVKQIIIUWFVEca9Koqrr6bJ9JxjGPVUKDq8xPDzf//Z"
    },
    {
        "id": 78,
        "name": "رئال",
        "is_visible": true,
        "created_at": "2023-01-27T05:43:01.288879Z",
        "updated_at": "2029-12-28T12:00:56Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/realistic_v2.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAfEAABBAEFAQAAAAAAAAAAAAACAAEDBQQHERIhIlH/xAAUAQEAAAAAAAAAAAAAAAAAAAAF/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQACIf/aAAwDAQACEQMRAD8AlOo9fDXZ9LDitwA6XBlfyLbkUIkT9N9d0REehIZ6X//Z"
    },
    {
        "id": 118,
        "name": "فیگور",
        "is_visible": true,
        "created_at": "2023-08-18T18:09:57.001461Z",
        "updated_at": "2029-12-28T12:00:56Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/figure_v3.1.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAgEAABBAIBBQAAAAAAAAAAAAACAAEDBAUREgYUITFB/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABkRAAMAAwAAAAAAAAAAAAAAAAABAwIhMv/aAAwDAQACEQMRAD8Ak6eKr9TYyjNluRlTi7KBo9AwQgROI6ZvnJ/PtERLT5QfTWTP/9k="
    },
    {
        "id": 116,
        "name": "ابسترکت",
        "is_visible": true,
        "created_at": "2023-07-22T15:23:40.158831Z",
        "updated_at": "2029-12-27T11:01:09Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/abstract_v2.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAfEAACAQQCAwAAAAAAAAAAAAABAgMABAURBhITQUL/xAAUAQEAAAAAAAAAAAAAAAAAAAAE/8QAHhEAAQQBBQAAAAAAAAAAAAAAAQACA0EEERITM1H/2gAMAwEAAhEDEQA/AIDm2ZucXyW7gxqQ21uyxy+JE2is0ak9Qd9Rv5GgPQFKUp0L3cbTrQSpcPH3dYqh4v/Z"
    },
    {
        "id": 89,
        "name": "غیرواقعی",
        "is_visible": true,
        "created_at": "2023-02-17T22:14:10.558063Z",
        "updated_at": "2029-12-25T12:00:00Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/photorealism.jpg",
        "is_premium": true,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAdEAACAgIDAQAAAAAAAAAAAAABAgADBBEFBhMS/8QAFAEBAAAAAAAAAAAAAAAAAAAABf/EABcRAQEBAQAAAAAAAAAAAAAAAAEAAlH/2gAMAwEAAhEDEQA/ALvWuKpo4LCR3OTWalepcmuu3wVh9eaFlJCAk6BJ1uIiJCxbk5f/2Q=="
    },
    {
        "id": 110,
        "name": "بچگانه",
        "is_visible": true,
        "created_at": "2023-07-07T19:10:36.21435Z",
        "updated_at": "2029-12-25T11:00:10Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/simple_design_v2.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAhEAACAgECBwAAAAAAAAAAAAABAgADBQQRBhITFCEiQf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAECETH/2gAMAwEAAhEDEQA/ALnA39rkeI6Sr3ouVtKdfUWuUBRDyr7+FBJ2HzeIiRtYFSt4f//Z"
    },
    {
        "id": 109,
        "name": "رترو سای‌فای",
        "is_visible": true,
        "created_at": "2023-06-30T17:09:58.117873Z",
        "updated_at": "2029-12-24T13:00:10Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/retro_sci-fi_v2.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAfEAABBAICAwAAAAAAAAAAAAABAAIDBAcxBQYREiH/xAAUAQEAAAAAAAAAAAAAAAAAAAAE/8QAGxEAAgEFAAAAAAAAAAAAAAAAAQIAAxITIUH/2gAMAwEAAhEDEQA/AJ3kHI/OU+yzVK7aAr142RxMfWbJ6NA0C7yQN/NIiJzgXGEoIuNdcn//2Q=="
    },
    {
        "id": 92,
        "name": "شبحگون",
        "is_visible": true,
        "created_at": "2023-03-21T15:20:59.361734Z",
        "updated_at": "2029-12-21T23:28:18.266916Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/spectralv2.jpg",
        "is_premium": true,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAgEAACAgEDBQAAAAAAAAAAAAABAgAEAwUHIRESFjFB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgT/xAAXEQADAQAAAAAAAAAAAAAAAAAAAQIR/9oADAMBAAIRAxEAPwCV3Forl8Yu2sjWbV7Q6trM+READt3dQqqoVV44AAH32SYiIbb1kcSsP//Z"
    },
    {
        "id": 108,
        "name": "استیم‌پانک",
        "is_visible": true,
        "created_at": "2023-06-16T17:35:20.247679Z",
        "updated_at": "2028-12-24T12:59:10Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/steampunk_v2.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAeEAABBAIDAQAAAAAAAAAAAAAEAAIDBgEFERIhE//EABQBAQAAAAAAAAAAAAAAAAAAAAX/xAAaEQACAgMAAAAAAAAAAAAAAAABAgADETFR/9oADAMBAAIRAxEAPwC/p9dJ3mtK2k9nsY8pZpMjohS2xxMz9XY4a3p5jxEREmx+mJFFzqf/2Q=="
    },
    {
        "id": 107,
        "name": "شبینه",
        "is_visible": true,
        "created_at": "2023-06-09T22:28:26.288676Z",
        "updated_at": "2028-12-24T12:00:10Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/nightly_v2.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAeEAACAgICAwAAAAAAAAAAAAABAgADBAUGERJRkf/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAGxEAAQQDAAAAAAAAAAAAAAAAAQACAyEEUXH/2gAMAwEAAhEDEQA/AJlved7zJ3OYLsl2WhxTWGttbxRVHQ7Lk+/sREYLjbwK2TUzwNlf/9k="
    },
    {
        "id": 105,
        "name": "کات وحشت",
        "is_visible": true,
        "created_at": "2023-05-26T21:30:18.445476Z",
        "updated_at": "2028-12-24T12:00:00Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/horror_cut_v2.1.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAeEAACAgICAwAAAAAAAAAAAAABAgADBAYREhVBYf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGhEAAgIDAAAAAAAAAAAAAAAAAAECAyIzcf/aAAwDAQACEQMRAD8Ale+XeW2FsvMqpNj49DcLWAqg1K3UD0B24HwCIiFUsEUbtkun/9k="
    },
    {
        "id": 106,
        "name": "ابسرد",
        "is_visible": true,
        "created_at": "2023-06-02T21:34:19.717953Z",
        "updated_at": "2028-12-23T12:00:00Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/the_absurd_v2.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAfEAAABgEFAAAAAAAAAAAAAAAAAQIDBBEFBgcSE0H/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABgRAAMBAQAAAAAAAAAAAAAAAAABAhIh/9oADAMBAAIRAxEAPwCU6t3Ny2QnMHOhYyQ6w0bROrQ5yUXYtVnS6u1H4AAIolZXBj//2Q=="
    },
    {
        "id": 97,
        "name": "موج رویا",
        "is_visible": true,
        "created_at": "2023-04-14T18:48:51.57043Z",
        "updated_at": "2028-12-08T12:00:10Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/dreamwave_v2.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAhEAAABAUFAAAAAAAAAAAAAAAAAQQFAgMGERIHEyMxUf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAGxEAAgMAAwAAAAAAAAAAAAAAAQIAAwQRIpH/2gAMAwEAAhEDEQA/AJgyagqaWb4G9GwU4qlHzZrUO9MI4uyyOK9vCAAD69FoubsfTK9LsEA5n//Z"
    },
    {
        "id": 96,
        "name": "کات بولیو",
        "is_visible": true,
        "created_at": "2023-04-07T18:51:34.103197Z",
        "updated_at": "2026-12-30T02:39:43Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/the_cut_bulio.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAfEAACAgEEAwAAAAAAAAAAAAABAwACBQQGETEhYYH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAA//EABgRAAIDAAAAAAAAAAAAAAAAAAABAhFR/9oADAMBAAIRAxEAPwCnsNOLZgbudg8c1rdZqmWtYM7Lr+BxfgAdD0PsREk5PRSP/9k="
    },
    {
        "id": 95,
        "name": "کات",
        "is_visible": true,
        "created_at": "2023-04-07T18:51:34.103197Z",
        "updated_at": "2026-12-29T02:39:43Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/the_cut.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAdEAABBAMBAQAAAAAAAAAAAAADAAECBAUGEjFB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAZEQADAAMAAAAAAAAAAAAAAAAAAQIRITH/2gAMAwEAAhEDEQA/AKTp+mFyGNPIG1bNjqwLJaoKlOyNhCGOXMWj2OT+N9d0RFF9EysLR//Z"
    },
    {
        "id": 94,
        "name": "ترسناک",
        "is_visible": true,
        "created_at": "2023-04-07T18:51:34.103197Z",
        "updated_at": "2026-12-28T02:38:13Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/gloomy_v2.jpg",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAEAAQDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAgEAACAQMEAwAAAAAAAAAAAAABAgADBREEBhIhMVFx/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/xAAaEQACAgMAAAAAAAAAAAAAAAAAAQIDEiEx/9oADAMBAAIRAxEAPwCcvui+Agvc9TVBA4io2RTUdBF9KMePsRETHiJllccno//Z"
    },
    {
        "id": 83,
        "name": "اکسپرسیونیست",
        "is_visible": true,
        "created_at": "2023-02-10T05:55:41.217404Z",
        "updated_at": "2025-12-13T23:28:18.266916Z",
        "deleted_at": null,
        "photo_url": "https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/expressionism2.png",
        "is_premium": false,
        "model_type": "diffusion",
        "is_new": false,
        "blurDataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVR4nAE0AMv/AHShgZhdN6sbLTMAMQC83e7h//mYtLkADZQAu4SOnaLAUpnSbcDzAKaTpjhLW9eUO/9VJYo0GaWV284TAAAAAElFTkSuQmCC"
    }
]